movies/urls.py
from django.urls import path
from . import views

# so we dont need to name like movie_index django aware of this app_name use it in html by like this {% url "movie:index" %}
app_name = "movie"

urlpatterns = [
    path('home', views.home1, name="home1"),
    path('', views.index, name="index"),
    path('<int:movieid>', views.detail, name='detail')
]

moviesite/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views
# we havn't created url in api so this movie_resource.urls check resource_name
movie_resource = MovieResource()

urlpatterns = [
    path("", views.home),
    path('admin/', admin.site.urls),
    path("movies/", include("movies.urls")),
    path("api/", include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = "movies"
        excludes = ["date_created"]

movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Genre(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=50)
    year = models.IntegerField()
    rating = models.FloatField()
    stock_available = models.IntegerField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()
    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movieid):

    details = get_object_or_404(Movie, pk=movieid)
    return render(request, "movies/detail.html", {"details": details})


def home1(request):
    return render(request, "home.html")

moviesite/views.py
from django.shortcuts import render


def home(request):
    return render(request, "home.html")

movies/templates/movies/detail.html
{% extends 'base.html' %}


{% block content %}

<dl>
    <dt>TITLE</dt>
    <dd>{{details.title}}</dd>
    <dt>RATING</dt>
    <dd>{{details.rating}}</dd>
    <dt>STOCKS AVAILABLE</dt>
    <dd>{{details.stock_available}}</dd>
</dl>

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}


<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>S.NO</th>
            <th>TITLE</th>
            <th>GENRE</th>
            <th>RATING</th>
            <th>YEAR</th>
        </tr>
    </thead>

    <tfoot>
        {% for movie in movies %}
        <tr>
            <td>{{movie.id}}</td>
            <td>
                <a href='{% url "movie:detail" movie.id %}'>{{movie.title}}</a>
            </td>
            <td>{{movie.genre}}</td>
            <td>{{movie.rating}}</td>
            <td>{{movie.year}}</td>
        </tr>
    </tfoot>
    {% endfor %}
</table>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Movies Website</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Movie Webs</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'movie:home1' %}">HOME</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="admin/login">ADMIN LOGIN</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}{% endblock content %}
    </main>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}

<div><a href="{%  url 'movie:index' %}">MOVIES</a></div>

<div><a href="admin/login">ADMIN</a></div>


{% endblock %}